[package]
name = "game-web"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
axum = "0.7"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
tokio = { version = "1.37", features = ["macros", "rt-multi-thread"] }
