[server]
host = "0.0.0.0"
port = 8080
workers = 8
request_timeout_secs = 60

[database]
url = "postgres://vallheru:vallheru@localhost:5432/vallheru"
pool_size = 16
connect_timeout_secs = 10

[templates]
template_root = "../templates"
hot_reload = true

[features]
enable_registration = true
enable_world_map = false
